### ISSUE TITLE
update dependencies in v.0.7.x post-RC patch release

### ISSUE THREAD

**Issue by brody2consult** [brodybits/rollup-plugin-size-snapshot#8]
__(updated)__

Updates wanted for more stable `v.0.7.2` patch release to be made from `patch-v0.7.x` branch:

- [ ] switch from unsupported `rollup-plugin-replace` to `@rollup/plugin-replace` (as now proposed in PR #8)
- [ ] drop support for Rollup pre-0.68 (as now proposed in PR #8)
- [ ] update some other dependencies (as now proposed in PR #8)

~~prerequisite: #7~~ ✅

__GENERAL RATIONALE:__

- It would be ideal to switch away from outdated Rollup plugin, if possible in `patch-v0.7.x` branch:
- Considering that `@rollup/plugin-replace` is not officially supported with Rollup pre-1.0, it would be ideal to avoid the need for testing & support with older Rollup 0.x versions if possible

__UPDATED PREREQUISITE(S):__

- [ ] ensure that downstream `react-recompose` is upgraded to use Rollup 0.68 (as now proposed in react-recompose/react-recompose#25)

__SOME IMPORTANT NOTES:__

- removing support for Rollup pre-0.68 is a BREAKING CHANGE and assumes:
  - the recent `v0.7.1-rc1` version of this fork is not to be considered "stable" (as now described in a commit message in PR #8)
  - downstream `react-recompose` is upgraded to use Rollup 0.68 (see TODO item above)
- switch to `@rollup/plugin-replace` with Rollup pre-1.0 results in an ugly installation warning message (tradeoff vs using unsupported Rollup plugin package, as described in a commit message)

---

__general strategy for stable `patch-v0.7.x` release:__

First release from `patch-v0.7.x` (`v0.7.1-rc1`) was not intended to be 100% stable, and it is now desired to drop Rollup pre-0.68 support as described above. Now that a version `patch-v0.7.x` is working with `react-recompose`, it is desired to make a more stable v0.7.x patch release with the changes described above.

**Comment by brody2consult** [comment]
I have updated this issue to be the anchor point to discuss updating both `patch-v0.7.x` branch and downstream `react-recompose` to abandon Rollup 0.65 in favor of Rollup 0.68, with a goal of replacing the unsupported `rollup-plugin-replace` dependency. The rationale & quick description of the tradeoff are now in the description of this issue.

Updates have already been proposed in the following PRs:

- https://github.com/react-recompose/react-recompose/pull/25
- PR #15

**Comment by brody2consult** [comment]
Closing now that patch-v0.7.x branch is retired as discussed in #16
